/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DaoException;
import javax.swing.JOptionPane;
import service.UsagerService;
import utils.PasswordUtils;

/**
 *
 * @author naysson
 */
public class WelcomePanel extends javax.swing.JPanel {

    private PanelContainer parentPanel;
    
    private PasswordUtils passwordUtils;
    
    private UsagerService usagerService;
    
    public final static String SUBTITLE = "Inscription/Connexion";
    
    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel(PanelContainer p) {
        initComponents();
        try
        {
            passwordUtils = PasswordUtils.getInstance();
            parentPanel = p;
            usagerService = new UsagerService();
        }catch(DaoException ex)
        {
            JOptionPane.showMessageDialog( null, ex.getMessage(), "Erreur fatale", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Méthode à utiliser pour vider les champs de connexion ou d'inscription.
     * @param inscription si true alors vidage des champs d'inscription, sinon vidage des champs de connexion.
     */
    private void viderChamps(boolean inscription)
    {
        if( inscription )
        {
            viewConfirmationInput.setText("");
            viewPrenomInput.setText("");
            viewNomInput.setText("");
            viewLoginInput.setText("");
            viewPasswordInput.setText("");
            viewNumeroInput.setText("");
        } else
        {
            viewLoginConnexionInput.setText("");
            viewMdpConnexionInput.setText("");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewNomLabel = new javax.swing.JLabel();
        viewPrenomLabel = new javax.swing.JLabel();
        viewLoginLabel = new javax.swing.JLabel();
        viewMdpLabel = new javax.swing.JLabel();
        viewConfirmationLabel = new javax.swing.JLabel();
        viewNumeroLabel = new javax.swing.JLabel();
        viewNomInput = new javax.swing.JTextField();
        viewPrenomInput = new javax.swing.JTextField();
        viewLoginInput = new javax.swing.JTextField();
        viewPasswordInput = new javax.swing.JPasswordField();
        viewConfirmationInput = new javax.swing.JPasswordField();
        viewNumeroInput = new javax.swing.JTextField();
        viewInscriptionButton = new javax.swing.JButton();
        viewLoginConnexionLabel = new javax.swing.JLabel();
        viewLoginConnexionInput = new javax.swing.JTextField();
        viewMdpConnexionLabel = new javax.swing.JLabel();
        viewMdpConnexionInput = new javax.swing.JPasswordField();
        viewConnexionButton = new javax.swing.JButton();

        viewNomLabel.setText("Nom");

        viewPrenomLabel.setText("Prenom");

        viewLoginLabel.setText("Login");

        viewMdpLabel.setText("Mot de passe");

        viewConfirmationLabel.setText("Confirmation");

        viewNumeroLabel.setText("Numéro de tel");

        viewInscriptionButton.setText("S'inscrire");
        viewInscriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInscriptionButtonActionPerformed(evt);
            }
        });

        viewLoginConnexionLabel.setText("Login");

        viewMdpConnexionLabel.setText("Mot de passe");

        viewConnexionButton.setText("Se connecter");
        viewConnexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewConnexionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewNomLabel)
                            .addComponent(viewPrenomLabel)
                            .addComponent(viewLoginLabel)
                            .addComponent(viewMdpLabel)
                            .addComponent(viewConfirmationLabel))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewNomInput)
                            .addComponent(viewPrenomInput)
                            .addComponent(viewPasswordInput)
                            .addComponent(viewLoginInput)
                            .addComponent(viewConfirmationInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewNumeroLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewInscriptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(viewNumeroInput))))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewMdpConnexionLabel)
                    .addComponent(viewLoginConnexionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewLoginConnexionInput)
                    .addComponent(viewMdpConnexionInput)
                    .addComponent(viewConnexionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewNomLabel)
                    .addComponent(viewNomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLoginConnexionLabel)
                    .addComponent(viewLoginConnexionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPrenomLabel)
                    .addComponent(viewPrenomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewMdpConnexionLabel)
                    .addComponent(viewMdpConnexionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLoginLabel)
                    .addComponent(viewLoginInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewConnexionButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewMdpLabel)
                    .addComponent(viewPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewConfirmationLabel)
                    .addComponent(viewConfirmationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewNumeroLabel)
                    .addComponent(viewNumeroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewInscriptionButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewInscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInscriptionButtonActionPerformed
        try
        {
            usagerService.inscrireUsager(
                    viewNomInput.getText(), 
                    viewPrenomInput.getText(),
                    viewLoginInput.getText(),
                    passwordUtils.encryptPassword( new String(viewPasswordInput.getPassword()) ),
                    passwordUtils.encryptPassword( new String(viewConfirmationInput.getPassword()) ),
                    viewNumeroInput.getText()
                    );
            
            System.out.println("WelcomePanel - utilisateur " + viewLoginInput.getText() + " inscrit.");
            viderChamps(true);
            
            // @todo a changer
            parentPanel.switchTo("welcome", WelcomePanel.SUBTITLE);
        } catch( DaoException | IllegalArgumentException ex)
        {
            
            JOptionPane.showMessageDialog( null, ex.getMessage(), "Erreur fatale", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewInscriptionButtonActionPerformed

    private void viewConnexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewConnexionButtonActionPerformed
        try
        {
            int idUsagerConnecte = usagerService.connecterUsager(
                    viewLoginConnexionInput.getText(), 
                    passwordUtils.encryptPassword( new String( viewMdpConnexionInput.getPassword() ) )
                    );
            
            System.out.println("WelcomePanel - utilisateur " + viewLoginConnexionInput.getText() + " connecté.");
            viderChamps(false);
            parentPanel.setSessionUsagerid(idUsagerConnecte);
            
            // @todo a changer
            parentPanel.switchTo("welcome", WelcomePanel.SUBTITLE);
        } catch( DaoException ex)
        {
            JOptionPane.showMessageDialog( null, ex.getMessage(), "Erreur fatale", JOptionPane.ERROR_MESSAGE);
        } catch( IllegalArgumentException ex)
        {
            JOptionPane.showMessageDialog( null, ex.getMessage(), "Erreur de connexion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewConnexionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField viewConfirmationInput;
    private javax.swing.JLabel viewConfirmationLabel;
    private javax.swing.JButton viewConnexionButton;
    private javax.swing.JButton viewInscriptionButton;
    private javax.swing.JTextField viewLoginConnexionInput;
    private javax.swing.JLabel viewLoginConnexionLabel;
    private javax.swing.JTextField viewLoginInput;
    private javax.swing.JLabel viewLoginLabel;
    private javax.swing.JPasswordField viewMdpConnexionInput;
    private javax.swing.JLabel viewMdpConnexionLabel;
    private javax.swing.JLabel viewMdpLabel;
    private javax.swing.JTextField viewNomInput;
    private javax.swing.JLabel viewNomLabel;
    private javax.swing.JTextField viewNumeroInput;
    private javax.swing.JLabel viewNumeroLabel;
    private javax.swing.JPasswordField viewPasswordInput;
    private javax.swing.JTextField viewPrenomInput;
    private javax.swing.JLabel viewPrenomLabel;
    // End of variables declaration//GEN-END:variables
}
