/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DaoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.StudentService;
import view.model.StudentListTable;

/**
 *
 * @author user
 */
public class WelcomePanel extends javax.swing.JPanel {

    private PanelContainer bPanel;
    
    public final static String SUBTITLE = "Welcome";
    
    private StudentService studentService;
    
    
    private void majStudentTable()
    {
        try
        {
            viewStudentTable.setModel(
                    new StudentListTable( 
                            studentService.getStudentCollection() 
                    )
            );
        } catch( DaoException | NullPointerException ex)
        {
             Logger.getLogger(WelcomePanel.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Impossible de récupérer la liste des étudiants.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Creates new form WelcomePanel
     * @param basePanel
     */
    public WelcomePanel(PanelContainer basePanel) {
        initComponents();
        try
        {
            studentService = StudentService.getInstance();            
        } catch( DaoException ex)
        {
            JOptionPane.showMessageDialog(null, "Problème de connexion à la base de données. Fermeture de l'application.", "Erreur fatale", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        majStudentTable();
            
        basePanel.setSubtitle(SUBTITLE);
        bPanel = basePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewStudentTable = new javax.swing.JTable();
        viewLabelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        viewFieldFirstName = new java.awt.TextField();
        viewFieldName = new java.awt.TextField();
        viewButtonRegister = new javax.swing.JButton();
        viewButtonDelete = new javax.swing.JButton();

        viewStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(viewStudentTable);

        viewLabelName.setText("Name :");

        jLabel1.setText("First Name :");

        viewFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFieldNameActionPerformed(evt);
            }
        });

        viewButtonRegister.setText("Register");
        viewButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonRegisterActionPerformed(evt);
            }
        });

        viewButtonDelete.setText("Delete");
        viewButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(viewLabelName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(viewFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(viewButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(viewFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewButtonRegister)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonRegisterActionPerformed
        String firstName = viewFieldFirstName.getText();
        String name = viewFieldName.getText();
        try
        {
            studentService.registerStudent(name, firstName);
            majStudentTable();
        } catch( DaoException ex)
        {
            Logger.getLogger(WelcomePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Impossible d'insérer l'étudiant " + name + " dans la base de données.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        catch( IllegalArgumentException ex)
        {
            Logger.getLogger(WelcomePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Saisie invalide : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_viewButtonRegisterActionPerformed

    private void viewFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFieldNameActionPerformed

    private void viewButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonDeleteActionPerformed
        //viewStudentTable.getSelectedRow();
        //viewStudentTable.getModel().getValueAt(WIDTH, WIDTH);
    }//GEN-LAST:event_viewButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewButtonDelete;
    private javax.swing.JButton viewButtonRegister;
    private java.awt.TextField viewFieldFirstName;
    private java.awt.TextField viewFieldName;
    private javax.swing.JLabel viewLabelName;
    private javax.swing.JTable viewStudentTable;
    // End of variables declaration//GEN-END:variables
}
